import { AppProps } from "next/app";
import Head from "next/head";
import "../styles/global.scss";
import AOS from "aos";
import "aos/dist/aos.css";
import { useEffect } from "react";
import AppWrapper from "@/components/AppWrapper";

const MyApp = ({ Component, pageProps }) => {
  const appName = process.env.NEXT_PUBLIC_APP_NAME || "Default App Name";

  useEffect(() => {
    AOS.init({
      duration: 1000, // Thời gian hiệu ứng (ms)
      easing: "ease-in-out", // Độ mượt của hiệu ứng
      once: false, // Chỉ chạy hiệu ứng 1 lần khi xuất hiện
    });
  }, []);

  return (
    <AppWrapper>
      <Head>
        <title>{appName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </AppWrapper>
  );
};

export default MyApp;
